services:
  db:
    image: postgres:17
    container_name: postgres_container1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: project
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
